# Form implementation generated from reading ui file 'AffairPeriodWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AffairPeriodWindow(object):
    def setupUi(self, AffairPeriodWindow):
        AffairPeriodWindow.setObjectName("AffairPeriodWindow")
        AffairPeriodWindow.resize(341, 180)
        self.centralwidget = QtWidgets.QWidget(parent=AffairPeriodWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_time_start = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_time_start.setFont(font)
        self.label_time_start.setObjectName("label_time_start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_time_start)
        self.time_start = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_start.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start.sizePolicy().hasHeightForWidth())
        self.time_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.time_start.setFont(font)
        self.time_start.setStyleSheet("border-style: none;\n"
"")
        self.time_start.setFrame(True)
        self.time_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.time_start.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToPreviousValue)
        self.time_start.setKeyboardTracking(False)
        self.time_start.setObjectName("time_start")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.time_start)
        self.label_time_end = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_time_end.setFont(font)
        self.label_time_end.setObjectName("label_time_end")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_time_end)
        self.time_end = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.time_end.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end.sizePolicy().hasHeightForWidth())
        self.time_end.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.time_end.setFont(font)
        self.time_end.setStyleSheet("border-style: none;\n"
"")
        self.time_end.setFrame(True)
        self.time_end.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.time_end.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToPreviousValue)
        self.time_end.setKeyboardTracking(False)
        self.time_end.setObjectName("time_end")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.time_end)
        self.label_name_affair = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_name_affair.setFont(font)
        self.label_name_affair.setObjectName("label_name_affair")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name_affair)
        self.name_affair = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_affair.setFont(font)
        self.name_affair.setText("")
        self.name_affair.setObjectName("name_affair")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name_affair)
        self.delete_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_button.setObjectName("delete_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.delete_button)
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.save_button)
        AffairPeriodWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AffairPeriodWindow)
        QtCore.QMetaObject.connectSlotsByName(AffairPeriodWindow)

    def retranslateUi(self, AffairPeriodWindow):
        _translate = QtCore.QCoreApplication.translate
        AffairPeriodWindow.setWindowTitle(_translate("AffairPeriodWindow", "MainWindow"))
        self.label_time_start.setText(_translate("AffairPeriodWindow", "Начало"))
        self.label_time_end.setText(_translate("AffairPeriodWindow", "Конец"))
        self.label_name_affair.setText(_translate("AffairPeriodWindow", "Дело"))
        self.delete_button.setText(_translate("AffairPeriodWindow", "Удалить"))
        self.save_button.setText(_translate("AffairPeriodWindow", "Сохранить"))

