# Form implementation generated from reading ui file 'AffairPeriodWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AffairPeriodWidget(object):
    def setupUi(self, AffairPeriodWidget):
        AffairPeriodWidget.setObjectName("AffairPeriodWidget")
        AffairPeriodWidget.resize(823, 47)
        font = QtGui.QFont()
        font.setPointSize(16)
        AffairPeriodWidget.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AffairPeriodWidget)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time_start = QtWidgets.QTimeEdit(parent=AffairPeriodWidget)
        self.time_start.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start.sizePolicy().hasHeightForWidth())
        self.time_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_start.setFont(font)
        self.time_start.setStyleSheet("")
        self.time_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.time_start.setKeyboardTracking(False)
        self.time_start.setObjectName("time_start")
        self.horizontalLayout_2.addWidget(self.time_start)
        self.separator_label = QtWidgets.QLabel(parent=AffairPeriodWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.separator_label.sizePolicy().hasHeightForWidth())
        self.separator_label.setSizePolicy(sizePolicy)
        self.separator_label.setObjectName("separator_label")
        self.horizontalLayout_2.addWidget(self.separator_label)
        self.time_end = QtWidgets.QTimeEdit(parent=AffairPeriodWidget)
        self.time_end.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end.sizePolicy().hasHeightForWidth())
        self.time_end.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.time_end.setFont(font)
        self.time_end.setStyleSheet("")
        self.time_end.setFrame(False)
        self.time_end.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.time_end.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToPreviousValue)
        self.time_end.setKeyboardTracking(False)
        self.time_end.setObjectName("time_end")
        self.horizontalLayout_2.addWidget(self.time_end)
        self.name_affair = QtWidgets.QLabel(parent=AffairPeriodWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_affair.sizePolicy().hasHeightForWidth())
        self.name_affair.setSizePolicy(sizePolicy)
        self.name_affair.setObjectName("name_affair")
        self.horizontalLayout_2.addWidget(self.name_affair)
        self.configure_button = QtWidgets.QPushButton(parent=AffairPeriodWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configure_button.sizePolicy().hasHeightForWidth())
        self.configure_button.setSizePolicy(sizePolicy)
        self.configure_button.setText("")
        self.configure_button.setObjectName("configure_button")
        self.horizontalLayout_2.addWidget(self.configure_button)

        self.retranslateUi(AffairPeriodWidget)
        QtCore.QMetaObject.connectSlotsByName(AffairPeriodWidget)

    def retranslateUi(self, AffairPeriodWidget):
        _translate = QtCore.QCoreApplication.translate
        AffairPeriodWidget.setWindowTitle(_translate("AffairPeriodWidget", "Form"))
        self.separator_label.setText(_translate("AffairPeriodWidget", "-"))
        self.name_affair.setText(_translate("AffairPeriodWidget", "TextLabel"))
