# Form implementation generated from reading ui file 'ChoiceSchedulePatternWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChoiceSchedulePatternWidget(object):
    def setupUi(self, ChoiceSchedulePatternWidget):
        ChoiceSchedulePatternWidget.setObjectName("ChoiceSchedulePatternWidget")
        ChoiceSchedulePatternWidget.resize(508, 209)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChoiceSchedulePatternWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choice_name = QtWidgets.QComboBox(parent=ChoiceSchedulePatternWidget)
        self.choice_name.setObjectName("choice_name")
        self.horizontalLayout.addWidget(self.choice_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.default_selection_buuton = QtWidgets.QPushButton(parent=ChoiceSchedulePatternWidget)
        self.default_selection_buuton.setObjectName("default_selection_buuton")
        self.horizontalLayout.addWidget(self.default_selection_buuton)
        self.create_schedule_pattern_button = QtWidgets.QPushButton(parent=ChoiceSchedulePatternWidget)
        self.create_schedule_pattern_button.setObjectName("create_schedule_pattern_button")
        self.horizontalLayout.addWidget(self.create_schedule_pattern_button)

        self.retranslateUi(ChoiceSchedulePatternWidget)
        QtCore.QMetaObject.connectSlotsByName(ChoiceSchedulePatternWidget)

    def retranslateUi(self, ChoiceSchedulePatternWidget):
        _translate = QtCore.QCoreApplication.translate
        ChoiceSchedulePatternWidget.setWindowTitle(_translate("ChoiceSchedulePatternWidget", "Form"))
        self.default_selection_buuton.setText(_translate("ChoiceSchedulePatternWidget", "Выбрать по умолчанию"))
        self.create_schedule_pattern_button.setText(_translate("ChoiceSchedulePatternWidget", "Создать"))
