# Form implementation generated from reading ui file 'ScheduleWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScheduleWindow(object):
    def setupUi(self, ScheduleWindow):
        ScheduleWindow.setObjectName("ScheduleWindow")
        ScheduleWindow.resize(853, 0)
        self.central_widget = QtWidgets.QWidget(parent=ScheduleWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab_widget = QtWidgets.QTabWidget(parent=self.central_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_tab_widget.setFont(font)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.schedule_day_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.schedule_day_tab.setFont(font)
        self.schedule_day_tab.setObjectName("schedule_day_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.schedule_day_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.schedule_day_layout = QtWidgets.QVBoxLayout()
        self.schedule_day_layout.setSpacing(2)
        self.schedule_day_layout.setObjectName("schedule_day_layout")
        self.verticalLayout_2.addLayout(self.schedule_day_layout)
        self.main_tab_widget.addTab(self.schedule_day_tab, "")
        self.schedule_pattern_tab = QtWidgets.QWidget()
        self.schedule_pattern_tab.setObjectName("schedule_pattern_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.schedule_pattern_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.schedule_pattern_layout = QtWidgets.QVBoxLayout()
        self.schedule_pattern_layout.setSpacing(2)
        self.schedule_pattern_layout.setObjectName("schedule_pattern_layout")
        self.verticalLayout_3.addLayout(self.schedule_pattern_layout)
        self.main_tab_widget.addTab(self.schedule_pattern_tab, "")
        self.verticalLayout.addWidget(self.main_tab_widget)
        ScheduleWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(parent=ScheduleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 26))
        self.menubar.setObjectName("menubar")
        ScheduleWindow.setMenuBar(self.menubar)

        self.retranslateUi(ScheduleWindow)
        self.main_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ScheduleWindow)

    def retranslateUi(self, ScheduleWindow):
        _translate = QtCore.QCoreApplication.translate
        ScheduleWindow.setWindowTitle(_translate("ScheduleWindow", "MainWindow"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.schedule_day_tab), _translate("ScheduleWindow", "Расписание"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.schedule_pattern_tab), _translate("ScheduleWindow", "Шаблоны"))
