# Form implementation generated from reading ui file 'ScheduleWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScheduleWidget(object):
    def setupUi(self, ScheduleWidget):
        ScheduleWidget.setObjectName("ScheduleWidget")
        ScheduleWidget.setEnabled(True)
        ScheduleWidget.resize(506, 378)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScheduleWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools = QtWidgets.QHBoxLayout()
        self.tools.setObjectName("tools")
        self.add_button = QtWidgets.QPushButton(parent=ScheduleWidget)
        self.add_button.setObjectName("pushButton")
        self.tools.addWidget(self.add_button)
        self.verticalLayout.addLayout(self.tools)
        self.scrollArea = QtWidgets.QScrollArea(parent=ScheduleWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.AffairArial = QtWidgets.QWidget()
        self.AffairArial.setGeometry(QtCore.QRect(0, 0, 504, 345))
        self.AffairArial.setObjectName("AffairArial")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.AffairArial)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.affair_period_widget_layout = QtWidgets.QVBoxLayout()
        self.affair_period_widget_layout.setSpacing(2)
        self.affair_period_widget_layout.setObjectName("affair_period_widget_layout")
        self.verticalLayout_2.addLayout(self.affair_period_widget_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.AffairArial)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(ScheduleWidget)
        QtCore.QMetaObject.connectSlotsByName(ScheduleWidget)

    def retranslateUi(self, ScheduleWidget):
        _translate = QtCore.QCoreApplication.translate
        ScheduleWidget.setWindowTitle(_translate("ScheduleWidget", "Form"))
        self.add_button.setText(_translate("ScheduleWidget", "Добавить"))
